### ISSUE TITLE
Naming standard for tasks

### ISSUE THREAD

**Issue by marco-roy** [acvos/gust#9]
I think we should ***enforce*** a certain standard on task naming in order to avoid conflicts, especially as we support more and more source types & modules.

Ex:

```
 read:
  type: nodejs
  module: fs-promise
  command: readFileSync
  inputs:
    path: fileName
    options: options
  outputs: [ data ]
```

Should probably be named `node.fs-promise.read` . This could also be the way to specify the `type` & `module`, so they don't have to be specified at all in the task declaration.

We should choose a delimiter that would otherwise not be used in task names; `.` is probably not the best pick.

This would also allow us to use multiple tasks that do the same thing simultaneously. Ex: `node.fs-promise.read` & `node.such-module.read-slowly`.

We could also manually override tasks if we wanted to, by specifying the replacement. Something like this:

```
node.such-module.read-slowly: node.fs-promise.read
```

Although we'd have to consolidate inputs & outputs somehow.
